# Generated by Django 5.0.2 on 2024-02-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default='Computer', help_text='Enter the Lecture name', max_length=255),
        ),
    ]
